site_name: Chad Rodgers - Pages
site_url: https://chaddrodgers.github.io/pages/
repo_url: https://github.com/ChadDRodgers/pages

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  custom_dir: overrides  # Point here if you need to override HTML templates

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Articles:
      - My Ideas: articles/ideas.md
      - Tutorials: articles/tutorials.md
  - About Me: about.md
